//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCDSteamRando.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SCDSteamRando.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //------------Sonic CD ActFinish Script-------------//
        /////--------Scripted by Christian Whitehead &apos;The Taxman&apos;--------//
        /////-------Unpacked By Rubberduckycooly&apos;s Script Unpacker-------//
        ///
        /////-------Aliases-------//
        ///#alias 4: TYPE_ACTFINISH
        ///
        ///
        ///sub ObjectMain
        ///	switch Object.State
        ///	case 0
        ///		Object.XPos=-799
        ///		Object.Value1=1168
        ///		Object.Value2=1255
        ///		Object.Value3=1319
        ///		Object.Value4=1402
        ///		Object.State=1
        ///		switch Stage.Minutes
        ///		case 0
        ///			if Stage.Seconds&lt;30
        ///				Object.Value5=50000
        ///			else
        ///				if Stage.Seconds&lt;4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ActFinish_template {
            get {
                return ResourceManager.GetString("ActFinish_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //------------Sonic CD LoadSaveMenu Script-------------//
        /////--------Scripted by Christian Whitehead &apos;The Taxman&apos;--------//
        /////-------Unpacked By Rubberduckycooly&apos;s Script Unpacker-------//
        ///
        /////-------Aliases-------//
        ///#alias 6: TYPE_LOADSAVEMENU
        ///
        ///// Function declarations
        ///#function LoadSaveMenu_Function2
        ///#function LoadSaveMenu_Function3
        ///#function LoadSaveMenu_Function4
        ///#function LoadSaveMenu_Function5
        ///
        ///function LoadSaveMenu_Function2
        ///	switch Object[+ArrayPos0].Rotation
        ///	case 2
        ///		if Object[+Array [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LoadSaveMenu_template {
            get {
                return ResourceManager.GetString("LoadSaveMenu_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //------------Sonic CD TimeWarp Script-------------//
        /////--------Scripted by Christian Whitehead &apos;The Taxman&apos;--------//
        /////-------Unpacked By Rubberduckycooly&apos;s Script Unpacker-------//
        ///
        /////-------Aliases-------//
        ///#alias 28: TYPE_TIMEWARP
        ///#alias Player.Value0:Player.Rings
        ///#alias Player.Value4:Player.Invincible
        ///#alias Player.Value6:Player.MinRollSpeed
        ///
        ///
        ///sub ObjectDraw
        ///	switch Object.State
        ///	case 0
        ///		if Object.Value1&lt;320
        ///			if Object.Value1==0
        ///				Player.Invincible=1000
        ///				Player.ControlMode=-1
        ///#platform: Mobile [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TimeWarp_template {
            get {
                return ResourceManager.GetString("TimeWarp_template", resourceCulture);
            }
        }
    }
}
