//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCDSteamRando.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SCDSteamRando.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //------------Sonic CD ActFinish Script-------------//
        /////--------Scripted by Christian Whitehead &apos;The Taxman&apos;--------//
        /////-------Unpacked By Rubberduckycooly&apos;s Script Unpacker-------//
        ///
        /////-------Aliases-------//
        ///#alias 4: TYPE_ACTFINISH
        ///
        ///// Function declarations
        ///#function ActFinish_NextStage
        ///#function ActFinish_LoadEnding
        ///
        ///function ActFinish_NextStage
        ///	switch Stage.ListPos
        /////REPLACE
        ///	endswitch
        ///endfunction
        ///
        ///function ActFinish_LoadEnding
        ///	if Options.GameMode==2
        ///		TimeAttack.Result=Stage.Seconds
        ///		TimeAttack.R [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ActFinish_template {
            get {
                return ResourceManager.GetString("ActFinish_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //------------Sonic CD AmyRose Script-------------//
        /////--------Scripted by Christian Whitehead &apos;The Taxman&apos;--------//
        /////-------Unpacked By Rubberduckycooly&apos;s Script Unpacker-------//
        ///
        /////-------Aliases-------//
        ///#alias 61: TYPE_AMYROSE
        ///
        ///
        ///sub ObjectMain
        ///	switch Object.State
        ///	case 0
        ///		Object.Frame=Object.Value0
        ///		Object.Frame&gt;&gt;=2
        ///		Object.Value0++
        ///		Object.Value0%=24
        ///		Object.XPos+=81920
        ///		ObjectTileGrip(0,0,19,0)
        ///		TempValue0=Object[-1].XPos
        ///		TempValue0-=6291456
        ///		if Object.XPos&gt;TempValue0        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Amy {
            get {
                return ResourceManager.GetString("Amy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //------------Sonic CD FuturePost Script-------------//
        /////--------Scripted by Christian Whitehead &apos;The Taxman&apos;--------//
        /////-------Unpacked By Rubberduckycooly&apos;s Script Unpacker-------//
        ///
        /////-------Aliases-------//
        ///#alias 16: TYPE_FUTUREPOST
        ///
        ///#function FuturePost_CheckLevel
        ///
        ///function FuturePost_CheckLevel
        ///	TempValue0=0
        ///	switch Stage.ListPos
        /////REPLACE
        ///		TempValue0=1
        ///	endswitch
        ///endfunction
        ///
        ///sub ObjectPlayerInteraction
        ///	if Object.State==0
        ///		if Player.CollisionPlane==Object.Value1
        ///			PlayerObj [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FuturePost_template {
            get {
                return ResourceManager.GetString("FuturePost_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //------------Sonic CD Goal Post Script-------------//
        /////--------Scripted by Christian Whitehead &apos;The Taxman&apos;--------//
        /////-------Unpacked By Rubberduckycooly&apos;s Script Unpacker-------//
        ///
        /////-------Aliases-------//
        ///#alias 19: TYPE_GOALPOST
        ///
        ///sub ObjectMain
        ///	if Object.State==0
        ///		TempValue0=Object.YPos
        ///		TempValue0+=6291456
        ///		if Player.YPos&lt;TempValue0
        ///			if Player.XPos&gt;Object.XPos
        ///				Stage.NewXBoundary1=Object.XPos
        ///				Stage.NewXBoundary1&gt;&gt;=16
        ///				Stage.NewXBoundary1-=160
        ///				CallFunction(FutureP [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GoalPost {
            get {
                return ResourceManager.GetString("GoalPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //------------Sonic CD LoadSaveMenu Script-------------//
        /////--------Scripted by Christian Whitehead &apos;The Taxman&apos;--------//
        /////-------Unpacked By Rubberduckycooly&apos;s Script Unpacker-------//
        ///
        /////-------Aliases-------//
        ///#alias 6: TYPE_LOADSAVEMENU
        ///
        ///// Function declarations
        ///#function LoadSaveMenu_Function2
        ///#function LoadSaveMenu_Function3
        ///#function LoadSaveMenu_Function4
        ///#function LoadSaveMenu_Function5
        ///
        ///function LoadSaveMenu_Function2
        ///	switch Object[+ArrayPos0].Rotation
        ///	case 2
        ///		if Object[+Array [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LoadSaveMenu_template {
            get {
                return ResourceManager.GetString("LoadSaveMenu_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name=Randomizer
        ///Description=Randomizes the level order.
        ///Author=MainMemory
        ///TxtScripts=true
        ///.
        /// </summary>
        internal static string mod_ini {
            get {
                return ResourceManager.GetString("mod_ini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //------------Sonic CD PastPost Script-------------//
        /////--------Scripted by Christian Whitehead &apos;The Taxman&apos;--------//
        /////-------Unpacked By Rubberduckycooly&apos;s Script Unpacker-------//
        ///
        /////-------Aliases-------//
        ///#alias 17: TYPE_PASTPOST
        ///
        ///
        ///sub ObjectPlayerInteraction
        ///	if Object.State==0
        ///		if Player.CollisionPlane==Object.Value1
        ///			PlayerObjectCollision(C_TOUCH,-8,-24,8,32)
        ///			if CheckResult==1
        ///				Warp.Destination=1
        ///				Object.State=1
        ///				Object.Priority=1
        ///				Object.Frame=1
        ///				PlaySfx(13,0) [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PastPost {
            get {
                return ResourceManager.GetString("PastPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //------------Sonic CD Special Ring Script-------------//
        /////--------Scripted by Christian Whitehead &apos;The Taxman&apos;--------//
        /////-------Unpacked By Rubberduckycooly&apos;s Script Unpacker-------//
        ///
        /////-------Aliases-------//
        ///#alias 20: TYPE_SPECIALRING
        ///#alias Player.Value0:Player.Rings
        ///
        ///sub ObjectMain
        ///	if Object.State==0
        ///		if Player.Rings&gt;49
        ///			PlayerObjectCollision(C_TOUCH,-16,-16,16,16)
        ///			if CheckResult==1
        ///				Object[0].Type=TypeName[BlankObject]
        ///				Object[1].Type=TypeName[BlankObject]
        ///				Player.C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SpecialRing_template {
            get {
                return ResourceManager.GetString("SpecialRing_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //------------Sonic CD TimeWarp Script-------------//
        /////--------Scripted by Christian Whitehead &apos;The Taxman&apos;--------//
        /////-------Unpacked By Rubberduckycooly&apos;s Script Unpacker-------//
        ///
        /////-------Aliases-------//
        ///#alias 28: TYPE_TIMEWARP
        ///#alias Player.Value0:Player.Rings
        ///#alias Player.Value4:Player.Invincible
        ///#alias Player.Value6:Player.MinRollSpeed
        ///
        ///
        ///sub ObjectDraw
        ///	switch Object.State
        ///	case 0
        ///		if Object.Value1&lt;320
        ///			if Object.Value1==0
        ///				Player.Invincible=1000
        ///				Player.ControlMode=-1
        ///#platform: Mobile [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TimeWarp_template {
            get {
                return ResourceManager.GetString("TimeWarp_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //------------Sonic CD Water Script-------------//
        /////--------Scripted by Christian Whitehead &apos;The Taxman&apos;--------//
        /////-------Unpacked By Rubberduckycooly&apos;s Script Unpacker-------//
        ///
        /////-------Aliases-------//
        ///#alias 36: TYPE_WATER
        ///
        ///// Function declarations
        ///#function Water_CreateAirBubble
        ///#function Water_CreateCountBubble
        ///#function Water_Function49
        ///#function Water_Function50
        ///
        ///function Water_CreateAirBubble
        ///	if Object.Value1&gt;0
        ///		Object.Value1--
        ///		if Object.Value2&gt;0
        ///			Object.Value2--
        ///		else
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Water_template {
            get {
                return ResourceManager.GetString("Water_template", resourceCulture);
            }
        }
    }
}
